### ISSUE TITLE
Non alphanum filter value

### ISSUE THREAD

**Issue by bodji** [ActiveChooN/gin-gorm-filter#2]
Hi,

First, thank you for this amazing little gorm filtering module, very well thought, and super simple/easy to implement ! 

I open an issue to discuss about a problem we encounter.

This regex does not match non-alphanumerical value such as this string : "my-value-contains-hyphens" : 
```
re, err := regexp.Compile(fmt.Sprintf(`(?m)%v:(\w{1,}).*`, paramName))
```

I think this choice has been made to let user chose any non-alphanumerical character as a separator when you have multiple filters in the string.

On our fork, we decided to choose a fixed separator (we chose ` ,`) and replaced the regex with : 
```
re, err := regexp.Compile(fmt.Sprintf(`(?m)%v:([^,]*)`, paramName))
```

And now, the filters are working with any filter value :)

Do you think it could be integrated into the main code, or you want to let it like this ?

**Comment by ActiveChooN** [comment]
Hi @bodji,

Your proposal looks good and can help with non-alphanumerical parameters. Do you want to open related PR?
